import { Router } from 'express';
import { createHmac } from 'node:crypto';
import { nanoid } from 'nanoid';
import { prisma } from '../lib/prisma.js';
import { requireAuth, ADMIN_ROLES } from '../middleware/auth.js';
import { asyncHandler, badRequest, notFound, forbidden } from '../middleware/error.js';
import { env } from '../config/env.js';
import { sendEmail } from '../lib/email.js';
import { sendPush, tokensFor } from '../lib/push.js';
import { emitEntityEvent } from '../lib/realtime.js';

const router = Router();
router.use(requireAuth);

/**
 * Guardian pickup flow.
 *
 * Students can scan THEMSELVES into school with their ID card, but never out.
 * Leaving requires one of:
 *   - a parent's pickup QR  (PU1.<childId>.<sig> — HMAC-bound to the parent's
 *     registered email; also serves as the printable "home QR" for bus drop-offs)
 *   - a one-time delegate pass (OTP-… — created by a parent for a named person)
 *   - boarding the school bus (bus scan of the student ID)
 */

// Stable HOME code (PU1) — printable, left with whoever is at the house for a
// bus drop-off. Deliberately NOT accepted at the school gate: a printed code
// that never changes is a code anyone who photographs it can reuse.
const sig = (childId, parentEmail) =>
  createHmac('sha256', env.jwtSecret).update(`pickup|${childId}|${(parentEmail || '').toLowerCase()}`).digest('base64url').slice(0, 16);

// Rotating GATE code (PU2) — regenerated by the parent's app every few minutes
// and only valid around the window it was minted in, so a screenshot goes
// stale before it is worth anything.
const GATE_WINDOW_MS = 3 * 60 * 1000;
const windowNow = () => Math.floor(Date.now() / GATE_WINDOW_MS);
const rotSig = (childId, parentEmail, counter) =>
  createHmac('sha256', env.jwtSecret)
    .update(`pickup2|${childId}|${(parentEmail || '').toLowerCase()}|${counter}`)
    .digest('base64url')
    .slice(0, 16);

// How long a delegate pass stays usable after the child is actually collected.
const PASS_GRACE_MS = 2 * 60 * 60 * 1000; // 2 hours

const SCAN_ROLES = new Set(['security', 'school_bus_admin', ...ADMIN_ROLES]);

function parentOf(person, email) {
  const e = (email || '').toLowerCase();
  if ((person.father_email || '').toLowerCase() === e) return 'father';
  if ((person.mother_email || '').toLowerCase() === e) return 'mother';
  return null;
}

// GET /api/pickup/code/:childId — the signed pickup/home QR for THIS parent.
router.get(
  '/code/:childId',
  asyncHandler(async (req, res) => {
    const child = await prisma.person.findUnique({ where: { id: req.params.childId } });
    if (!child) throw notFound('Child not found');
    if (!parentOf(child, req.user.email) && !ADMIN_ROLES.has(req.role)) {
      throw forbidden('Only a registered parent can get this pickup code');
    }
    const email = parentOf(child, req.user.email) ? req.user.email : child.father_email || child.mother_email;
    const c = windowNow();
    res.json({
      // Show at the school gate. Rotates — the app refetches before it lapses.
      gate_code: `PU2.${child.id}.${c}.${rotSig(child.id, email, c)}`,
      rotates_in_ms: (c + 1) * GATE_WINDOW_MS - Date.now(),
      // Print and leave at home for the bus drop-off.
      home_code: `PU1.${child.id}.${sig(child.id, email)}`,
      // Back-compat for builds that predate rotating codes.
      code: `PU1.${child.id}.${sig(child.id, email)}`,
      child: { id: child.id, name: child.full_name },
      bound_to: email,
    });
  })
);

// POST /api/pickup/one-time — parent creates a delegate pass { child_id, person_name, phone }
router.post(
  '/one-time',
  asyncHandler(async (req, res) => {
    const { child_id, person_name, phone } = req.body || {};
    if (!child_id || !person_name?.trim()) throw badRequest('child_id and person_name are required');
    const child = await prisma.person.findUnique({ where: { id: child_id } });
    if (!child) throw notFound('Child not found');
    if (!parentOf(child, req.user.email)) throw forbidden('Only a registered parent can authorise a pickup');
    const pass = await prisma.oneTimePass.create({
      data: {
        school_id: child.school_id, parent_id: req.user.id, parent_name: req.user.full_name,
        child_id: child.id, child_name: child.full_name, purpose: 'pickup',
        authorized_person_name: person_name.trim(), contact_phone: phone || null,
        qr_code: `OTP-${nanoid(12)}`, status: 'active',
        valid_until: new Date(Date.now() + 24 * 3600 * 1000), created_by: req.user.email,
      },
    });
    res.status(201).json(pass);
  })
);

// GET /api/pickup/passes/:childId — passes this parent has issued, newest first.
router.get(
  '/passes/:childId',
  asyncHandler(async (req, res) => {
    const child = await prisma.person.findUnique({ where: { id: req.params.childId } });
    if (!child) throw notFound('Child not found');
    if (!parentOf(child, req.user.email) && !ADMIN_ROLES.has(req.role)) {
      throw forbidden('Only a registered parent can see these passes');
    }
    const rows = await prisma.oneTimePass.findMany({
      where: { child_id: child.id }, orderBy: { created_date: 'desc' }, take: 20,
    });
    const now = new Date();
    res.json(rows.map((p) => ({
      ...p,
      // Derived so the app never has to reimplement the expiry rule.
      is_live: p.status !== 'revoked' && p.status !== 'expired' && (!p.valid_until || p.valid_until > now),
    })));
  })
);

// POST /api/pickup/passes/:id/revoke — parent cancels a pass they shared.
router.post(
  '/passes/:id/revoke',
  asyncHandler(async (req, res) => {
    const pass = await prisma.oneTimePass.findUnique({ where: { id: req.params.id } });
    if (!pass) throw notFound('Pass not found');
    const child = await prisma.person.findUnique({ where: { id: pass.child_id } });
    if (!child || (!parentOf(child, req.user.email) && !ADMIN_ROLES.has(req.role))) {
      throw forbidden('Only the issuing parent can cancel this pass');
    }
    const updated = await prisma.oneTimePass.update({
      where: { id: pass.id }, data: { status: 'revoked' },
    });
    res.json(updated);
  })
);

async function notifyParents(child, { title, body }) {
  const emails = [child.father_email, child.mother_email].filter(Boolean);
  if (!emails.length) return;
  const users = await prisma.user.findMany({ where: { email: { in: emails } } });
  const tokens = users.map((u) => u.push_token).filter(Boolean);
  sendPush(tokens, { title, body, data: { type: 'pickup', person_id: child.id } }).catch(() => {});
  for (const to of emails) {
    sendEmail({ to, from_name: 'School Guardian', subject: title, body }).catch(() => {});
  }
}

// POST /api/pickup/scan — resolve + consume a pickup/home QR at the gate or bus.
// body: { code, context: 'gate' | 'bus', bus_id?, bus_name?, gate_name? }
router.post(
  '/scan',
  asyncHandler(async (req, res) => {
    if (!SCAN_ROLES.has(req.role)) throw forbidden('Only security or bus staff can scan pickups');
    const { code = '', context = 'gate', bus_id, bus_name, gate_name } = req.body || {};
    const when = new Date();
    const time = when.toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' });

    let child = null;
    let byLine = '';       // for logs
    let passType = '';

    if (code.startsWith('PU2.')) {
      // Rotating gate/home code: valid for its own window ±1, which absorbs
      // clock skew and the seconds between showing and scanning.
      const [, childId, counterRaw, s] = code.split('.');
      const counter = Number(counterRaw);
      if (!Number.isFinite(counter)) throw badRequest('Malformed pickup code');
      child = childId && (await prisma.person.findUnique({ where: { id: childId } }));
      if (!child) throw notFound('Unknown pickup code');
      const now = windowNow();
      if (Math.abs(now - counter) > 1) {
        throw badRequest('This pickup code has expired — ask the parent to reopen it in the app.');
      }
      const parentEmail = [child.father_email, child.mother_email]
        .filter(Boolean)
        .find((e) => rotSig(child.id, e, counter) === s);
      if (!parentEmail) throw badRequest('This pickup code is not valid for this child');
      byLine = `parent/guardian (${parentEmail})`;
      passType = 'parent_pickup';
    } else if (code.startsWith('PU1.')) {
      // Printable home code — for the bus drop-off only. At the gate we insist
      // on the rotating code so a photographed printout is useless there.
      if (context !== 'bus') {
        throw badRequest('This is a home drop-off code. At the gate the parent must show the live pickup QR from their app.');
      }
      const [, childId, s] = code.split('.');
      child = childId && (await prisma.person.findUnique({ where: { id: childId } }));
      if (!child) throw notFound('Unknown pickup code');
      const parentEmail = [child.father_email, child.mother_email].filter(Boolean).find((e) => sig(child.id, e) === s);
      if (!parentEmail) throw badRequest('This pickup code is not valid for this child');
      byLine = `household (code issued to ${parentEmail})`;
      passType = 'parent_pickup';
    } else if (code.startsWith('OTP-')) {
      const pass = await prisma.oneTimePass.findFirst({ where: { qr_code: code } });
      if (!pass) throw notFound('Unknown pass');
      if (pass.status === 'expired') throw badRequest('This pickup pass has expired');
      if (pass.status === 'revoked') throw badRequest('This pickup pass was cancelled by the parent');
      if (pass.valid_until && pass.valid_until < when) {
        await prisma.oneTimePass.update({ where: { id: pass.id }, data: { status: 'expired' } });
        throw badRequest(
          pass.used_at
            ? 'This pickup pass expired two hours after the child was collected.'
            : 'This pickup pass has expired.'
        );
      }
      child = await prisma.person.findUnique({ where: { id: pass.child_id } });
      if (!child) throw notFound('Child on this pass no longer exists');

      // The pass dies two hours AFTER the child is collected, not instantly:
      // the same code still has to work for the bus drop-off, and a guard
      // re-scanning to check a name should not be locked out. Only the first
      // scan starts that clock.
      if (!pass.used_at) {
        await prisma.oneTimePass.update({
          where: { id: pass.id },
          data: { used_at: when, valid_until: new Date(when.getTime() + PASS_GRACE_MS), status: 'used' },
        });
      }
      byLine = `${pass.authorized_person_name} (authorised by ${pass.parent_name || 'parent'})`;
      passType = 'one_time';
    } else {
      throw badRequest('Not a pickup code');
    }

    if (context === 'bus') {
      if (!bus_id) throw badRequest('bus_id is required for bus drop-offs');
      await prisma.busScanLog.create({
        data: {
          school_id: child.school_id, bus_id, bus_name: bus_name || null,
          person_id: child.id, person_name: child.full_name, person_category: child.category,
          action: 'alight', timestamp: when,
          scanned_by: req.user.full_name || 'Bus staff', scanned_by_name: req.user.full_name || 'Bus staff',
          notes: `Received at home by ${byLine}`,
        },
      });
      await prisma.person.update({ where: { id: child.id }, data: { current_status: 'outside' } });
      notifyParents(child, {
        title: `${child.full_name} dropped off at home`,
        body: `${child.full_name} was dropped off by ${bus_name || 'the school bus'} at ${time} and received by ${byLine}.`,
      });
      emitEntityEvent('BusScanLog', 'create', undefined, child.school_id);
      return res.json({ ok: true, action: 'dropoff', child: { id: child.id, name: child.full_name }, by: byLine });
    }

    await prisma.accessLog.create({
      data: {
        school_id: child.school_id, person_id: child.id, person_name: child.full_name,
        person_category: child.category, action: 'exit', timestamp: when,
        scanned_by: req.user.full_name || 'Security', gate_name: gate_name || req.user.gate_name || 'Main Gate',
        pass_type: passType, notes: `Picked up by ${byLine}`,
      },
    });
    await prisma.person.update({ where: { id: child.id }, data: { current_status: 'outside' } });
    notifyParents(child, {
      title: `${child.full_name} left school`,
      body: `${child.full_name} was signed out at ${time}, picked up by ${byLine}.`,
    });
    emitEntityEvent('AccessLog', 'create', undefined, child.school_id);
    res.json({ ok: true, action: 'pickup', child: { id: child.id, name: child.full_name }, by: byLine });
  })
);

export default router;
